apiVersion: apps/v1
kind: Deployment
metadata:
  name: villa-website:latest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: villa-website:latest
  template:
    metadata:
      labels:
        app: villa-website:latest
    spec:
      containers:
        - name: villa-website:latest
          image: vijay1770/villa-website
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served  by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground
 
 
