apiVersion: apps/v1
kind: Deployment
metadata:
  name: villa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: villa
  template:
    metadata:
      labels:
        app: villa
    spec:
      containers:
      - name: villa
        image: <your-dockerhub-username>/villa-website:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: villa-service
spec:
  type: LoadBalancer
  selector:
    app: villa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
